// In-process BDD runner. Drives `run()` exactly the way the real binary does,
// against a per-scenario temp config-dir + fixture-dir, and appends a Markdown
// evidence block to `evidence/<feature>.md`.
//
// The bdd-evidence-reviewer subagent reads the .feature spec and the evidence
// file together; this runner's job is to make each step honestly verifiable
// (quoted output, file contents, exit code) without paraphrasing.

import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync, appendFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { run } from '../../src/cli/run.js';
import { FakeProvider } from '../../src/infrastructure/fake-provider.js';
import { JsonProfileRepository } from '../../src/infrastructure/json-profile-repository.js';
import { fixedClock } from '../../src/infrastructure/system-clock.js';
import type { Adapter, Profile } from '../../src/domain/types.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const EVIDENCE_DIR = resolve(HERE, '../../evidence');
// Derive the demo identifier (e.g. "002-save-and-dry-run-gui") from the
// runner's own path. Prior to demo-002 this was hardcoded, which silently
// shipped "Demo: 001-save-and-dry-run-cli" headers into demo-002's evidence
// files when the runner was copied forward. Path-derived survives copy.
const DEMO_DIR = basename(resolve(HERE, '../..'));

const FIXED_NOW = '2026-05-19T12:00:00.000Z';

export interface ScenarioEnv {
  configDir: string;
  fixtureDir: string;
  profilesPath: string;
  adaptersPath: string;
}

export function makeScenarioEnv(opts: {
  adapters: Adapter[];
  profiles?: Profile[];
}): ScenarioEnv {
  const root = mkdtempSync(join(tmpdir(), 'winnetpro-bdd-'));
  const configDir = join(root, 'demo-config');
  const fixtureDir = join(configDir, 'fixtures');
  mkdirSync(fixtureDir, { recursive: true });
  const adaptersPath = join(fixtureDir, 'adapters.json');
  writeFileSync(adaptersPath, JSON.stringify(opts.adapters, null, 2));
  const profilesPath = join(configDir, 'profiles.json');
  if (opts.profiles && opts.profiles.length > 0) {
    writeFileSync(profilesPath, JSON.stringify(opts.profiles, null, 2));
  }
  return { configDir, fixtureDir, profilesPath, adaptersPath };
}

export interface RunResult {
  exitCode: number;
  stdout: string;
  stderr: string;
  // The live FakeProvider instance used by this run. Tests read
  // `provider.mutationLog` to prove no mutation occurred — a real
  // observation of the live array, not an in-process placeholder.
  provider: FakeProvider;
}

export async function runCli(
  env: ScenarioEnv,
  command: string,
  opts: { isTTY?: boolean } = {},
): Promise<RunResult> {
  const argv = ['--config-dir', env.configDir, '--fixture-dir', env.fixtureDir, ...tokenize(command)];
  const outBufs: string[] = [];
  const errBufs: string[] = [];
  const provider = new FakeProvider({ fixtureDir: env.fixtureDir });
  const repository = new JsonProfileRepository(env.configDir);
  const exitCode = await run(argv, {
    stdin: { isTTY: opts.isTTY ?? false },
    stdout: { write: (s: string) => outBufs.push(s) },
    stderr: { write: (s: string) => errBufs.push(s) },
    cwd: () => env.configDir,
  }, {
    provider,
    repository,
    clock: fixedClock(FIXED_NOW),
  });
  return { exitCode, stdout: outBufs.join(''), stderr: errBufs.join('') , provider };
}

function tokenize(s: string): string[] {
  // Shell-ish: split on whitespace, but respect double-quoted values.
  const out: string[] = [];
  let i = 0;
  while (i < s.length) {
    while (i < s.length && /\s/.test(s[i]!)) i += 1;
    if (i >= s.length) break;
    if (s[i] === '"') {
      i += 1;
      let v = '';
      while (i < s.length && s[i] !== '"') {
        v += s[i];
        i += 1;
      }
      if (s[i] === '"') i += 1;
      out.push(v);
    } else {
      let v = '';
      while (i < s.length && !/\s/.test(s[i]!)) {
        v += s[i];
        i += 1;
      }
      out.push(v);
    }
  }
  return out;
}

export function cleanup(env: ScenarioEnv): void {
  // env.configDir is inside the tmpdir-based root; remove the parent.
  rmSync(dirname(env.configDir), { recursive: true, force: true });
}

export function resetEvidence(featureFile: string, featureTitle: string): string {
  mkdirSync(EVIDENCE_DIR, { recursive: true });
  const path = join(EVIDENCE_DIR, `${featureFile}.md`);
  const header = [
    `# Evidence — ${featureFile}.feature`,
    ``,
    `Feature: ${featureTitle}`,
    ``,
    `Demo: ${DEMO_DIR}`,
    `Provider: fake`,
    `Clock (deterministic for evidence): ${FIXED_NOW}`,
    `Generated by: tsx --test tests/bdd/${featureFile}.test.ts`,
    ``,
    `Source feature file: [docs/bdd/${featureFile}.feature](../../../docs/bdd/${featureFile}.feature)`,
    ``,
  ].join('\n');
  writeFileSync(path, header);
  return path;
}

export interface ScenarioBlock {
  scenario: string;
  status: 'PASS' | 'FAIL';
  steps: string[];
  stdout?: string;
  stderr?: string;
  exitCode?: number;
  // Pre-run state files (fixture / seed profiles) — shown so the audience can
  // verify the Given preconditions independently, not just trust the runner.
  setupFiles?: { path: string; contents: string }[];
  // Post-run state files (e.g. profiles.json after a save).
  files?: { path: string; contents: string }[];
  fakeMutationLog?: unknown;
  notes?: string[];
}

export function appendScenario(evidencePath: string, block: ScenarioBlock): void {
  const lines: string[] = [];
  lines.push('');
  lines.push(`## Scenario: ${block.scenario}`);
  lines.push('');
  lines.push(`**Status:** ${block.status}`);
  lines.push('');
  lines.push('### Steps');
  for (const s of block.steps) lines.push(`- ${s}`);
  if (block.exitCode !== undefined) {
    lines.push('');
    lines.push(`### Exit code`);
    lines.push('```');
    lines.push(String(block.exitCode));
    lines.push('```');
  }
  if (block.stdout !== undefined && block.stdout.length > 0) {
    lines.push('');
    lines.push('### Stdout');
    lines.push('```');
    lines.push(block.stdout.trimEnd());
    lines.push('```');
  }
  if (block.stderr !== undefined && block.stderr.length > 0) {
    lines.push('');
    lines.push('### Stderr');
    lines.push('```');
    lines.push(block.stderr.trimEnd());
    lines.push('```');
  }
  if (block.setupFiles !== undefined && block.setupFiles.length > 0) {
    for (const f of block.setupFiles) {
      lines.push('');
      lines.push(`### Setup file (pre-run): ${f.path}`);
      lines.push('```json');
      lines.push(f.contents.trimEnd());
      lines.push('```');
    }
  }
  if (block.files !== undefined && block.files.length > 0) {
    for (const f of block.files) {
      lines.push('');
      lines.push(`### File: ${f.path}`);
      lines.push('```json');
      lines.push(f.contents.trimEnd());
      lines.push('```');
    }
  }
  if (block.fakeMutationLog !== undefined) {
    lines.push('');
    lines.push('### Fake provider mutation log (read from live FakeProvider instance)');
    lines.push('```json');
    lines.push(JSON.stringify(block.fakeMutationLog, null, 2));
    lines.push('```');
  }
  if (block.notes !== undefined && block.notes.length > 0) {
    lines.push('');
    lines.push('### Notes');
    for (const n of block.notes) lines.push(`- ${n}`);
  }
  lines.push('');
  appendFileSync(evidencePath, lines.join('\n'));
}

export function readFileIfExists(path: string): string | null {
  return existsSync(path) ? readFileSync(path, 'utf8') : null;
}
